theme: jekyll-theme-cayman
title: Luca-Lucian Frumuselu
description: MSc Finance @ UCL | Quantitative Research | Asset Management
url: "https://lucalucianfrumuselu.github.io"
author: Luca-Lucian Frumuselu
email: lucalucian.frumuselu@gmail.com
